# Generated by Django 4.0.3 on 2022-07-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('status', models.CharField(choices=[('در انتظار', 'Waiting'), ('هدایت شده به بانک', 'Redirect To Bank'), ('بازگشته از بانک', 'Return From Bank'), ('لغو توسط کاربر', 'Cancel By User'), ('توکن منقضی شده', 'Expire Gateway Token'), ('تاییدیه پرداخت منقضی شده', 'Expire Verify Payment'), ('تکمیل شده', 'Complete')], max_length=50, verbose_name='وضعیت')),
                ('bank_type', models.CharField(choices=[('BMI', 'ملی'), ('SEP', 'سپه'), ('ZARINPAL', 'زرین پال'), ('IDPAY', 'آیدی پی'), ('ZIBAL', 'زیبال'), ('BAHAMTA', 'باهمتا'), ('MELLAT', 'ملت')], max_length=50, verbose_name='بانک')),
                ('tracking_code', models.CharField(max_length=255, verbose_name='کد پیگیری')),
                ('amount', models.CharField(max_length=10, verbose_name='مبلغ')),
                ('reference_number', models.CharField(max_length=255, unique=True, verbose_name='رفرنس')),
                ('response_result', models.TextField(blank=True, null=True, verbose_name='نتیجه بانک')),
                ('callback_url', models.TextField(verbose_name='آدرس کال بک')),
                ('extra_information', models.TextField(blank=True, null=True, verbose_name='اطلاعات تکمیلی')),
                ('bank_choose_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه بانک انتخابی')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
    ]
