# Generated by Django 4.0.3 on 2022-07-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.CharField(choices=[('Waiting', 'در انتظار'), ('Redirect to bank', 'هدایت شده به بانک'), ('Return from bank', 'بازگشته از بانک'), ('Cancel by user', 'لغو توسط کاربر'), ('Expire gateway token', 'توکن منقضی شده'), ('Expire verify payment', 'تاییدیه پرداخت منقضی شده'), ('Complete', 'تکمیل شده')], max_length=50, verbose_name='وضعیت'),
        ),
    ]
